

obj-y := barrier.o


# CONFIG_MODULE_SIG=n

# CC = i586-poky-linux-gcc
# ARCH = x86
# CROSS_COMPILE = i586-poky-linux-
# SROOT=/opt/iot-devkit/1.7.3/sysroots/i586-poky-linux/

# KERNELDIR := /lib/modules/$(shell uname -r)/build
# CLEANFILE := *.dis *.o *.ko *.mod.* *.symvers *.*.old *.order *.cmd
# obj-m := barrier.o

# default:
	
# 	#make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(SROOT)/usr/src/kernel M=$(PWD) modules
# 	make -C $(KERNELDIR)  M=$(CURDIR) modules
# 	i586-poky-linux-gcc main.c -std=c11 -o main -Wall -lpthread --sysroot=$(SROOT)
	
# clean:
# 	rm main
# 	rm -f $(CLEANFILE)
	
